[package]
name = "today-folder"
version = "0.1.0"
authors = ["Angela-1 <ruoshui_engr@163.com>"]
edition = "2018"

[dependencies]
time = { version = "0.2", default-features = false }
chrono = { version = "0.4", features = ["serde"] }